import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { useState } from 'react';

import TerminalHeader from '@/components/TerminalHeader';
import CommandPrompt from '@/components/CommandPrompt';
import CommandOutput from '@/components/CommandOutput';

export default function Home() {
	const [inputText, setInputText] = useState('');
	const [commands, setCommands] = useState(['help', 'todo']);
	const now = new Date();
	const options = {
		weekday: 'short', year: 'numeric', month: 'short',
		hour: 'numeric', minute: 'numeric',
		timeZoneName: 'short'
	} as DateTimeFormat;

	const addCommandOutput = (e: any) => {
		e.preventDefault();
		if (inputText === 'clear') {
			setCommands([]);
		} else {
			setCommands([...commands, inputText]);
		}

		setInputText('');
	};

	return (
		<>
			<Head>
				<title>Resume - Tarryn S</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<div className="mx-auto max-w-xl rounded border border-gray-700 bg-gray-900 font-mono text-xs leading-snug text-gray-300 shadow-xl md:my-6 lg:my-10" >
					<TerminalHeader></TerminalHeader>

					<div className="px-2">
						<div className="mb-4">
							<span>Last login: </span>
							<span id="datetime">{new Intl.DateTimeFormat('en-US', options).format(now)}</span>
							<span> on ttys02</span>
						</div>

						{commands.map((command, index) => (<CommandOutput key={index} command={command}></CommandOutput>))}

						<CommandPrompt inputText={inputText}>
							<form onSubmit={addCommandOutput} className="inline absolute -top-4 opacity-0 w-full">
								<input autoFocus className="mt-4 w-full" value={inputText} onChange={e => setInputText(e.target.value)} />
							</form>
						</CommandPrompt>
					</div>
				</div>
			</main>
		</>
	)
}
